name: Auto Populate Seed Data

on:
  workflow_dispatch:
  push:
    paths:
      - 'seed-structure/**'
      - 'lib/schema.js'
      - 'scripts/autoPopulateSeedData.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: node scripts/autoPopulateSeedData.js
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-populated seed data"
